### ISSUE TITLE
Error with slop 4.0.0

### ISSUE THREAD

**Issue by parroty** [r7kamura/ruboty#9]
Hi. I was trying out ruboty, and facing the following errors at `rake spec` command (Error message is indicating that `Slop.parse!` is missing). 

```
Failures:

  1) Ruboty::Commands::Generate#call with normal condition generates ./ruboty/ directory from our templates
     Failure/Error: Ruboty::CommandBuilder.new(arguments).build
     NoMethodError:
       undefined method `parse!' for Slop:Module
     # ./lib/ruboty/command_builder.rb:22:in `options'
     # ./lib/ruboty/command_builder.rb:18:in `command_class'
     # ./lib/ruboty/command_builder.rb:12:in `build'
     # ./spec/ruboty/commands/generate_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./spec/ruboty/commands/generate_spec.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/ruboty/commands/generate_spec.rb:23:in `block (4 levels) in <top (required)>'

...2 more errors continue...
```

It seems the newer slop is just released (with some breaking changes), and causing the error. It may be good to limit the slop version, or adjust the code to latest version?

Some notes are,
- It seems the 4.0.0 is released on 12/27
  - https://rubygems.org/gems/slop/versions/4.0.0
- The last section of the readme is indicating `Slop.parse!` deprecation.
  - https://github.com/leejarvis/slop
- I used ruby 2.2.0/2.0.0, and both were the same result.
